
development:
  adapter: postgresql
  encoding: unicode
  database: ibc
  host: localhost
  pool: 5
  port: 5432
  username: postgres
  password: mobscene

production:
  adapter: postgresql
  encoding: unicode
  database: ibc
  host: localhost
  pool: 5
  port: 5432
  username: postgres
  password: mobscene
